// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, broker, account_number, account_type, currency, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, broker, account_number, account_type, currency, current_balance, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	UserID        int32  `json:"user_id"`
	Name          string `json:"name"`
	Broker        string `json:"broker"`
	AccountNumber string `json:"account_number"`
	AccountType   string `json:"account_type"`
	Currency      string `json:"currency"`
	IsActive      bool   `json:"is_active"`
}

type CreateAccountRow struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	Name           string         `json:"name"`
	Broker         string         `json:"broker"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Currency       string         `json:"currency"`
	CurrentBalance sql.NullString `json:"current_balance"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Broker,
		arg.AccountNumber,
		arg.AccountType,
		arg.Currency,
		arg.IsActive,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountNumber,
		&i.AccountType,
		&i.Currency,
		&i.CurrentBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, broker, account_number, account_type, currency, current_balance, is_active, created_at, updated_at
FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetAccountByIDRow struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	Name           string         `json:"name"`
	Broker         string         `json:"broker"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Currency       string         `json:"currency"`
	CurrentBalance sql.NullString `json:"current_balance"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (GetAccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.UserID)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountNumber,
		&i.AccountType,
		&i.Currency,
		&i.CurrentBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, name, broker, account_number, account_type, currency, current_balance, is_active, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetAccountsByUserIDRow struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	Name           string         `json:"name"`
	Broker         string         `json:"broker"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Currency       string         `json:"currency"`
	CurrentBalance sql.NullString `json:"current_balance"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID int32) ([]GetAccountsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsByUserIDRow
	for rows.Next() {
		var i GetAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Broker,
			&i.AccountNumber,
			&i.AccountType,
			&i.Currency,
			&i.CurrentBalance,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3,
    broker = $4,
    account_number = $5,
    account_type = $6,
    currency = $7,
    is_active = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, broker, account_number, account_type, currency, current_balance, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	ID            int32  `json:"id"`
	UserID        int32  `json:"user_id"`
	Name          string `json:"name"`
	Broker        string `json:"broker"`
	AccountNumber string `json:"account_number"`
	AccountType   string `json:"account_type"`
	Currency      string `json:"currency"`
	IsActive      bool   `json:"is_active"`
}

type UpdateAccountRow struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	Name           string         `json:"name"`
	Broker         string         `json:"broker"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Currency       string         `json:"currency"`
	CurrentBalance sql.NullString `json:"current_balance"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Broker,
		arg.AccountNumber,
		arg.AccountType,
		arg.Currency,
		arg.IsActive,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountNumber,
		&i.AccountType,
		&i.Currency,
		&i.CurrentBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET current_balance = current_balance + $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, broker, account_number, account_type, currency, current_balance, is_active, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

type UpdateAccountBalanceRow struct {
	ID             int32          `json:"id"`
	UserID         int32          `json:"user_id"`
	Name           string         `json:"name"`
	Broker         string         `json:"broker"`
	AccountNumber  string         `json:"account_number"`
	AccountType    string         `json:"account_type"`
	Currency       string         `json:"currency"`
	CurrentBalance sql.NullString `json:"current_balance"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (UpdateAccountBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, updateAccountBalance, arg.ID, arg.UserID, arg.CurrentBalance)
	var i UpdateAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountNumber,
		&i.AccountType,
		&i.Currency,
		&i.CurrentBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
