// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: strategies.sql

package db

import (
	"context"
	"database/sql"
)

const createStrategy = `-- name: CreateStrategy :one
INSERT INTO strategies (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, description, created_at, updated_at
`

type CreateStrategyParams struct {
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateStrategy(ctx context.Context, arg CreateStrategyParams) (Strategy, error) {
	row := q.db.QueryRowContext(ctx, createStrategy, arg.UserID, arg.Name, arg.Description)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStrategy = `-- name: DeleteStrategy :execresult
DELETE FROM strategies
WHERE id = $1 AND user_id = $2
`

type DeleteStrategyParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteStrategy(ctx context.Context, arg DeleteStrategyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStrategy, arg.ID, arg.UserID)
}

const getStrategiesByUserID = `-- name: GetStrategiesByUserID :many
SELECT id, user_id, name, description, created_at, updated_at FROM strategies
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetStrategiesByUserID(ctx context.Context, userID int32) ([]Strategy, error) {
	rows, err := q.db.QueryContext(ctx, getStrategiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strategy
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStrategyByID = `-- name: GetStrategyByID :one
SELECT id, user_id, name, description, created_at, updated_at FROM strategies
WHERE id = $1 AND user_id = $2
`

type GetStrategyByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetStrategyByID(ctx context.Context, arg GetStrategyByIDParams) (Strategy, error) {
	row := q.db.QueryRowContext(ctx, getStrategyByID, arg.ID, arg.UserID)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStrategy = `-- name: UpdateStrategy :one
UPDATE strategies
SET name = $2, description = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, name, description, created_at, updated_at
`

type UpdateStrategyParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      int32          `json:"user_id"`
}

func (q *Queries) UpdateStrategy(ctx context.Context, arg UpdateStrategyParams) (Strategy, error) {
	row := q.db.QueryRowContext(ctx, updateStrategy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
