// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trades.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addTradeStrategy = `-- name: AddTradeStrategy :exec
INSERT INTO trade_strategies (trade_id, strategy_id) VALUES ($1, $2)
`

type AddTradeStrategyParams struct {
	TradeID    int32 `json:"trade_id"`
	StrategyID int32 `json:"strategy_id"`
}

func (q *Queries) AddTradeStrategy(ctx context.Context, arg AddTradeStrategyParams) error {
	_, err := q.db.ExecContext(ctx, addTradeStrategy, arg.TradeID, arg.StrategyID)
	return err
}

const createTrade = `-- name: CreateTrade :one
INSERT INTO
    trades (
        user_id,
        account_id,
        date,
        time,
        pair,
        type,
        entry,
        exit,
        lots,
        pips,
        pl,
        rr,
        status,
        stop_loss,
        take_profit,
        notes,
        mistakes,
        amount
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18
    )
RETURNING
    id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
`

type CreateTradeParams struct {
	UserID     int32          `json:"user_id"`
	AccountID  sql.NullInt32  `json:"account_id"`
	Date       time.Time      `json:"date"`
	Time       time.Time      `json:"time"`
	Pair       sql.NullString `json:"pair"`
	Type       TradeType      `json:"type"`
	Entry      sql.NullString `json:"entry"`
	Exit       sql.NullString `json:"exit"`
	Lots       sql.NullString `json:"lots"`
	Pips       sql.NullString `json:"pips"`
	Pl         sql.NullString `json:"pl"`
	Rr         sql.NullString `json:"rr"`
	Status     TradeStatus    `json:"status"`
	StopLoss   sql.NullString `json:"stop_loss"`
	TakeProfit sql.NullString `json:"take_profit"`
	Notes      sql.NullString `json:"notes"`
	Mistakes   sql.NullString `json:"mistakes"`
	Amount     sql.NullString `json:"amount"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, createTrade,
		arg.UserID,
		arg.AccountID,
		arg.Date,
		arg.Time,
		arg.Pair,
		arg.Type,
		arg.Entry,
		arg.Exit,
		arg.Lots,
		arg.Pips,
		arg.Pl,
		arg.Rr,
		arg.Status,
		arg.StopLoss,
		arg.TakeProfit,
		arg.Notes,
		arg.Mistakes,
		arg.Amount,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.Time,
		&i.Pair,
		&i.Type,
		&i.Entry,
		&i.Exit,
		&i.Lots,
		&i.Pips,
		&i.Pl,
		&i.Rr,
		&i.Status,
		&i.StopLoss,
		&i.TakeProfit,
		&i.Notes,
		&i.Mistakes,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrade = `-- name: DeleteTrade :exec
DELETE FROM trades WHERE id = $1 AND user_id = $2
`

type DeleteTradeParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTrade(ctx context.Context, arg DeleteTradeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTrade, arg.ID, arg.UserID)
	return err
}

const deleteTradeStrategies = `-- name: DeleteTradeStrategies :exec
DELETE FROM trade_strategies WHERE trade_id = $1
`

func (q *Queries) DeleteTradeStrategies(ctx context.Context, tradeID int32) error {
	_, err := q.db.ExecContext(ctx, deleteTradeStrategies, tradeID)
	return err
}

const getTradeByID = `-- name: GetTradeByID :one
SELECT id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at FROM trades WHERE id = $1 AND user_id = $2
`

type GetTradeByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetTradeByID(ctx context.Context, arg GetTradeByIDParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, getTradeByID, arg.ID, arg.UserID)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.Time,
		&i.Pair,
		&i.Type,
		&i.Entry,
		&i.Exit,
		&i.Lots,
		&i.Pips,
		&i.Pl,
		&i.Rr,
		&i.Status,
		&i.StopLoss,
		&i.TakeProfit,
		&i.Notes,
		&i.Mistakes,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTradeStrategies = `-- name: GetTradeStrategies :many
SELECT s.id, s.user_id, s.name, s.description, s.created_at, s.updated_at
FROM
    strategies s
    INNER JOIN trade_strategies ts ON s.id = ts.strategy_id
WHERE
    ts.trade_id = $1
`

func (q *Queries) GetTradeStrategies(ctx context.Context, tradeID int32) ([]Strategy, error) {
	rows, err := q.db.QueryContext(ctx, getTradeStrategies, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strategy
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByAccountID = `-- name: GetTradesByAccountID :many
SELECT id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
FROM trades
WHERE
    account_id = $1
    AND user_id = $2
ORDER BY date DESC, time DESC
`

type GetTradesByAccountIDParams struct {
	AccountID sql.NullInt32 `json:"account_id"`
	UserID    int32         `json:"user_id"`
}

func (q *Queries) GetTradesByAccountID(ctx context.Context, arg GetTradesByAccountIDParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, getTradesByAccountID, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Date,
			&i.Time,
			&i.Pair,
			&i.Type,
			&i.Entry,
			&i.Exit,
			&i.Lots,
			&i.Pips,
			&i.Pl,
			&i.Rr,
			&i.Status,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Notes,
			&i.Mistakes,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByAccountIDAndDateRange = `-- name: GetTradesByAccountIDAndDateRange :many
SELECT id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
FROM trades
WHERE
    account_id = $1
    AND user_id = $2
    AND date >= $3
    AND date <= $4
ORDER BY date DESC, time DESC
`

type GetTradesByAccountIDAndDateRangeParams struct {
	AccountID sql.NullInt32 `json:"account_id"`
	UserID    int32         `json:"user_id"`
	Date      time.Time     `json:"date"`
	Date_2    time.Time     `json:"date_2"`
}

func (q *Queries) GetTradesByAccountIDAndDateRange(ctx context.Context, arg GetTradesByAccountIDAndDateRangeParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, getTradesByAccountIDAndDateRange,
		arg.AccountID,
		arg.UserID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Date,
			&i.Time,
			&i.Pair,
			&i.Type,
			&i.Entry,
			&i.Exit,
			&i.Lots,
			&i.Pips,
			&i.Pl,
			&i.Rr,
			&i.Status,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Notes,
			&i.Mistakes,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByUserID = `-- name: GetTradesByUserID :many
SELECT id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
FROM trades
WHERE
    user_id = $1
ORDER BY date DESC, time DESC
`

func (q *Queries) GetTradesByUserID(ctx context.Context, userID int32) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, getTradesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Date,
			&i.Time,
			&i.Pair,
			&i.Type,
			&i.Entry,
			&i.Exit,
			&i.Lots,
			&i.Pips,
			&i.Pl,
			&i.Rr,
			&i.Status,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Notes,
			&i.Mistakes,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByUserIDAndDateRange = `-- name: GetTradesByUserIDAndDateRange :many
SELECT id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
FROM trades
WHERE
    user_id = $1
    AND date >= $2
    AND date <= $3
ORDER BY date DESC, time DESC
`

type GetTradesByUserIDAndDateRangeParams struct {
	UserID int32     `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetTradesByUserIDAndDateRange(ctx context.Context, arg GetTradesByUserIDAndDateRangeParams) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, getTradesByUserIDAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Date,
			&i.Time,
			&i.Pair,
			&i.Type,
			&i.Entry,
			&i.Exit,
			&i.Lots,
			&i.Pips,
			&i.Pl,
			&i.Rr,
			&i.Status,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Notes,
			&i.Mistakes,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrade = `-- name: UpdateTrade :one
UPDATE trades
SET
    account_id = $2,
    date = $3,
    time = $4,
    pair = $5,
    type = $6,
    entry = $7,
    exit = $8,
    lots = $9,
    pips = $10,
    pl = $11,
    rr = $12,
    status = $13,
    stop_loss = $14,
    take_profit = $15,
    notes = $16,
    mistakes = $17,
    amount = $18,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
    AND user_id = $19
RETURNING
    id, user_id, account_id, date, time, pair, type, entry, exit, lots, pips, pl, rr, status, stop_loss, take_profit, notes, mistakes, amount, created_at, updated_at
`

type UpdateTradeParams struct {
	ID         int32          `json:"id"`
	AccountID  sql.NullInt32  `json:"account_id"`
	Date       time.Time      `json:"date"`
	Time       time.Time      `json:"time"`
	Pair       sql.NullString `json:"pair"`
	Type       TradeType      `json:"type"`
	Entry      sql.NullString `json:"entry"`
	Exit       sql.NullString `json:"exit"`
	Lots       sql.NullString `json:"lots"`
	Pips       sql.NullString `json:"pips"`
	Pl         sql.NullString `json:"pl"`
	Rr         sql.NullString `json:"rr"`
	Status     TradeStatus    `json:"status"`
	StopLoss   sql.NullString `json:"stop_loss"`
	TakeProfit sql.NullString `json:"take_profit"`
	Notes      sql.NullString `json:"notes"`
	Mistakes   sql.NullString `json:"mistakes"`
	Amount     sql.NullString `json:"amount"`
	UserID     int32          `json:"user_id"`
}

func (q *Queries) UpdateTrade(ctx context.Context, arg UpdateTradeParams) (Trade, error) {
	row := q.db.QueryRowContext(ctx, updateTrade,
		arg.ID,
		arg.AccountID,
		arg.Date,
		arg.Time,
		arg.Pair,
		arg.Type,
		arg.Entry,
		arg.Exit,
		arg.Lots,
		arg.Pips,
		arg.Pl,
		arg.Rr,
		arg.Status,
		arg.StopLoss,
		arg.TakeProfit,
		arg.Notes,
		arg.Mistakes,
		arg.Amount,
		arg.UserID,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Date,
		&i.Time,
		&i.Pair,
		&i.Type,
		&i.Entry,
		&i.Exit,
		&i.Lots,
		&i.Pips,
		&i.Pl,
		&i.Rr,
		&i.Status,
		&i.StopLoss,
		&i.TakeProfit,
		&i.Notes,
		&i.Mistakes,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
